// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, Thiago!");

var a = {
  contents: 1
};

a.contents = 2;

a.contents = 2;

console.log("Hello, Thiago! " + String(a.contents) + "");

exports.a = a;
/*  Not a pure module */
